# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed4a013b7dc34144e6d4b15bec0cacd8433424b5c492235007dec3ef7f0704f899c1c41910affa7cb6861d233984afd24e28a7b4efc154b45e9cc9e50fd69f06

test:
  secret_key_base: e63cc495cb04d03907d20403476c320c8c53e2ea86c5896d2166a3df91135a5a4fbecd0ed775935f82870726d205e5aa16e834112b93b2df1d5c304a264edbbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
